#include "pch.h"
#include "Warcraft3Types.h"

/// Holds information about Warcraft 3 - type hierarchies.
namespace Warcraft3Types {

	std::map<std::string, std::string> INHERITENCE = {
		{ "agent"			   , "handle" },
		{ "event"              , "agent" },
		{ "player"             , "agent" },
		{ "widget"             , "agent" },
		{ "unit"               , "widget" },
		{ "destructable"       , "widget" },
		{ "item"               , "widget" },
		{ "ability"            , "agent" },
		{ "buff"               , "ability" },
		{ "force"              , "agent" },
		{ "group"              , "agent" },
		{ "trigger"            , "agent" },
		{ "triggercondition"   , "agent" },
		{ "triggeraction"      , "handle" },
		{ "timer"              , "agent" },
		{ "location"           , "agent" },
		{ "region"             , "agent" },
		{ "rect"               , "agent" },
		{ "boolexpr"           , "agent" },
		{ "sound"              , "agent" },
		{ "conditionfunc"      , "boolexpr" },
		{ "filterfunc"         , "boolexpr" },
		{ "unitpool"           , "handle" },
		{ "itempool"           , "handle" },
		{ "race"               , "handle" },
		{ "alliancetype"       , "handle" },
		{ "racepreference"     , "handle" },
		{ "gamestate"          , "handle" },
		{ "igamestate"         , "gamestate" },
		{ "fgamestate"         , "gamestate" },
		{ "playerstate"        , "handle" },
		{ "playerscore"        , "handle" },
		{ "playergameresult"   , "handle" },
		{ "unitstate"          , "handle" },
		{ "aidifficulty"       , "handle" },
		{ "eventid"            , "handle" },
		{ "gameevent"          , "eventid" },
		{ "playerevent"        , "eventid" },
		{ "playerunitevent"    , "eventid" },
		{ "unitevent"          , "eventid" },
		{ "limitop"            , "eventid" },
		{ "widgetevent"        , "eventid" },
		{ "dialogevent"        , "eventid" },
		{ "unittype"           , "handle" },
		{ "gamespeed"          , "handle" },
		{ "gamedifficulty"     , "handle" },
		{ "gametype"           , "handle" },
		{ "mapflag"            , "handle" },
		{ "mapvisibility"      , "handle" },
		{ "mapsetting"         , "handle" },
		{ "mapdensity"         , "handle" },
		{ "mapcontrol"         , "handle" },
		{ "playerslotstate"    , "handle" },
		{ "volumegroup"        , "handle" },
		{ "camerafield"        , "handle" },
		{ "camerasetup"        , "handle" },
		{ "playercolor"        , "handle" },
		{ "placement"          , "handle" },
		{ "startlocprio"       , "handle" },
		{ "raritycontrol"      , "handle" },
		{ "blendmode"          , "handle" },
		{ "texmapflags"        , "handle" },
		{ "effect"             , "agent" },
		{ "effecttype"         , "handle" },
		{ "weathereffect"      , "handle" },
		{ "terraindeformation" , "handle" },
		{ "fogstate"           , "handle" },
		{ "fogmodifier"        , "agent" },
		{ "dialog"             , "agent" },
		{ "button"             , "agent" },
		{ "quest"              , "agent" },
		{ "questitem"          , "agent" },
		{ "defeatcondition"    , "agent" },
		{ "timerdialog"        , "agent" },
		{ "leaderboard"        , "agent" },
		{ "multiboard"         , "agent" },
		{ "multiboarditem"     , "agent" },
		{ "trackable"          , "agent" },
		{ "gamecache"          , "agent" },
		{ "version"            , "handle" },
		{ "itemtype"           , "handle" },
		{ "texttag"            , "handle" },
		{ "attacktype"         , "handle" },
		{ "damagetype"         , "handle" },
		{ "weapontype"         , "handle" },
		{ "soundtype"          , "handle" },
		{ "lightning"          , "handle" },
		{ "pathingtype"        , "handle" },
		{ "image"              , "handle" },
		{ "ubersplat"          , "handle" },
		{ "hashtable"          , "agent" },

		// UjAPI-extended fields
		{ "mousebuttontype"					, "handle" },
		{ "framehandle"						, "agent" },
		{ "originframetype"					, "handle" },
		{ "framepointtype"					, "handle" },
		{ "textaligntype"					, "handle" },
		{ "frameeventtype"					, "handle" },
		{ "oskeytype"						, "handle" },
		{ "armortype"						, "handle" },
		{ "heroattribute"					, "handle" },
		{ "defensetype"						, "handle" },
		{ "regentype"						, "handle" },
		{ "unitcategory"					, "handle" },
		{ "commandbuttoneffect"				, "handle" },
		{ "mapdatatype"						, "handle" },
		{ "projectiletype"					, "handle" },
		{ "mappedfield"						, "handle" },
		{ "mappedtype"						, "handle" },
		{ "attachmenttype"					, "mappedtype" },
		{ "bonetype"						, "attachmenttype" },
		{ "animtype"						, "mapdatatype" },
		{ "subanimtype"						, "animtype" },
		{ "cursoranimtype"					, "mapdatatype" },
		{ "war3image"						, "agent" },
		{ "sprite"							, "war3image" },
		{ "projectile"						, "war3image" },
		{ "doodad"							, "war3image" },
		{ "agentdatafield"					, "handle" },
		{ "unitstringfield"					, "agentdatafield" },
		{ "unitrealfield"					, "agentdatafield" },
		{ "unitintegerfield"				, "agentdatafield" },
		{ "unitbooleanfield"				, "agentdatafield" },
		{ "itemstringfield"					, "agentdatafield" },
		{ "itemrealfield"					, "agentdatafield" },
		{ "itemintegerfield"				, "agentdatafield" },
		{ "itembooleanfield"				, "agentdatafield" },
		{ "destructablestringfield"			, "agentdatafield" },
		{ "destructablerealfield"			, "agentdatafield" },
		{ "destructableintegerfield"		, "agentdatafield" },
		{ "destructablebooleanfield"		, "agentdatafield" },
		{ "abilitystringfield"				, "agentdatafield" },
		{ "abilityrealfield"				, "agentdatafield" },
		{ "abilityintegerfield"				, "agentdatafield" },
		{ "abilitybooleanfield"				, "agentdatafield" },
		{ "abilityreallevelfield"			, "agentdatafield" },
		{ "abilityintegerlevelfield"		, "agentdatafield" },
		{ "abilitystringlevelfield"			, "agentdatafield" },
		{ "abilitybooleanlevelfield"		, "agentdatafield" },
		{ "unitweaponstringfield"			, "agentdatafield" },
		{ "unitweaponrealfield"				, "agentdatafield" },
		{ "unitweaponintegerfield"			, "agentdatafield" },
		{ "unitweaponbooleanfield"			, "agentdatafield" },
		{ "abilityintegerlevelfield"		, "abilityintegerfield" },
		{ "abilityreallevelfield"			, "abilityrealfield" },
		{ "abilitybooleanlevelfield"		, "abilitybooleanfield" },
		{ "abilitystringlevelfield"			, "abilitystringfield" },
		{ "abilityintegerlevelarrayfield"	, "abilityintegerlevelfield" },
		{ "abilityreallevelarrayfield"		, "abilityreallevelfield" },
		{ "abilitybooleanlevelarrayfield"	, "abilitybooleanlevelfield" },
		{ "abilitystringlevelarrayfield"	, "abilitystringlevelfield" },
		{ "flagtype"						, "handle" },
		{ "layoutstyleflag"					, "flagtype" },
		{ "gridstyleflag"					, "flagtype" },
		{ "layerstyleflag"					, "flagtype" },
		{ "controlstyleflag"				, "flagtype" },
		{ "framestate"						, "flagtype" },
		{ "abilitytype"						, "flagtype" },
		{ "movetype"						, "flagtype" },
		{ "pathingaitype"					, "flagtype" },
		{ "collisiontype"					, "flagtype" },
		{ "targetflag"						, "flagtype" },
		{ "pathingflag"						, "flagtype" },
		{ "timetype"						, "handle" },
		{ "variabletype"					, "handle" },
		{ "renderstage"						, "handle" },
		{ "connectiontype"					, "handle" },
		{ "jassthread"						, "handle" },
		{ "handlelist"						, "agent" },
		{ "textfilehandle"					, "agent" },
		{ "orderhandle"						, "agent" },
		{ "tradestate"						, "handle" },
	};

	bool IsChild(const std::string& maintype, std::string childtype) {
		do {
			if (maintype == childtype) {
				return true;
			}

			childtype = INHERITENCE[childtype];
		} while (!childtype.empty());

		return false;
	}
}